# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ingest_pb2 as ingest__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ingest_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IngestStub:
    """차량 → 수집 게이트웨이 업링크.

    신원은 이 메시지에 없다. `vehicle_id`는 클라이언트 인증서 SAN URI에서만 나오고
    (SDD S-11), 차량이 메타데이터 `x-vehicle-id`로 보낸 값은 대조용 "주장"일 뿐이다.
    불일치하면 PERMISSION_DENIED로 스트림이 끊긴다.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Stream = channel.stream_stream(
                '/fleetsentinel.ingest.v1.Ingest/Stream',
                request_serializer=ingest__pb2.IngestRecord.SerializeToString,
                response_deserializer=ingest__pb2.Ack.FromString,
                _registered_method=True)


class IngestServicer:
    """차량 → 수집 게이트웨이 업링크.

    신원은 이 메시지에 없다. `vehicle_id`는 클라이언트 인증서 SAN URI에서만 나오고
    (SDD S-11), 차량이 메타데이터 `x-vehicle-id`로 보낸 값은 대조용 "주장"일 뿐이다.
    불일치하면 PERMISSION_DENIED로 스트림이 끊긴다.
    """

    def Stream(self, request_iterator, context):
        """양방향 스트림. 차량이 레코드를 밀고, 게이트웨이가 CACK을 돌려준다.

        요구 메타데이터:
        x-vehicle-id : 차량이 주장하는 ID. 인증서와 대조된다
        x-boot-id    : 이 스트림을 여는 WAL 세션의 boot_id (ULID)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IngestServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Stream': grpc.stream_stream_rpc_method_handler(
                    servicer.Stream,
                    request_deserializer=ingest__pb2.IngestRecord.FromString,
                    response_serializer=ingest__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fleetsentinel.ingest.v1.Ingest', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fleetsentinel.ingest.v1.Ingest', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Ingest:
    """차량 → 수집 게이트웨이 업링크.

    신원은 이 메시지에 없다. `vehicle_id`는 클라이언트 인증서 SAN URI에서만 나오고
    (SDD S-11), 차량이 메타데이터 `x-vehicle-id`로 보낸 값은 대조용 "주장"일 뿐이다.
    불일치하면 PERMISSION_DENIED로 스트림이 끊긴다.
    """

    @staticmethod
    def Stream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/fleetsentinel.ingest.v1.Ingest/Stream',
            ingest__pb2.IngestRecord.SerializeToString,
            ingest__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SegmentUploadStub:
    """── 중량 경로 제어 평면 ────────────────────────────────────────────────

    원시 센서 클립(MCAP, 298~341 MiB)은 **이 채널로 흐르지 않는다.** 게이트웨이는
    presigned URL만 발급하고 데이터는 차량 → 오브젝트 스토리지로 직행한다.
    게이트웨이를 데이터 경로에 넣으면 100대에서
    2.5 GiB/s가 통과해 stateless 확장 이점이 사라진다.

    **REST가 아니라 gRPC인 이유** — 이 채널은 이미 mTLS로 종단되고
    PeerIdentityInterceptor 가 vehicle_id 를 인증서에서 확정한다. 별도 HTTPS
    엔드포인트를 두면 인증 경로가 둘이 되고 언젠가 어긋난다.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Begin = channel.unary_unary(
                '/fleetsentinel.ingest.v1.SegmentUpload/Begin',
                request_serializer=ingest__pb2.BeginUploadRequest.SerializeToString,
                response_deserializer=ingest__pb2.BeginUploadResponse.FromString,
                _registered_method=True)
        self.Complete = channel.unary_unary(
                '/fleetsentinel.ingest.v1.SegmentUpload/Complete',
                request_serializer=ingest__pb2.CompleteUploadRequest.SerializeToString,
                response_deserializer=ingest__pb2.CompleteUploadResponse.FromString,
                _registered_method=True)
        self.Refresh = channel.unary_unary(
                '/fleetsentinel.ingest.v1.SegmentUpload/Refresh',
                request_serializer=ingest__pb2.RefreshUrlsRequest.SerializeToString,
                response_deserializer=ingest__pb2.BeginUploadResponse.FromString,
                _registered_method=True)
        self.Abort = channel.unary_unary(
                '/fleetsentinel.ingest.v1.SegmentUpload/Abort',
                request_serializer=ingest__pb2.AbortUploadRequest.SerializeToString,
                response_deserializer=ingest__pb2.AbortUploadResponse.FromString,
                _registered_method=True)


class SegmentUploadServicer:
    """── 중량 경로 제어 평면 ────────────────────────────────────────────────

    원시 센서 클립(MCAP, 298~341 MiB)은 **이 채널로 흐르지 않는다.** 게이트웨이는
    presigned URL만 발급하고 데이터는 차량 → 오브젝트 스토리지로 직행한다.
    게이트웨이를 데이터 경로에 넣으면 100대에서
    2.5 GiB/s가 통과해 stateless 확장 이점이 사라진다.

    **REST가 아니라 gRPC인 이유** — 이 채널은 이미 mTLS로 종단되고
    PeerIdentityInterceptor 가 vehicle_id 를 인증서에서 확정한다. 별도 HTTPS
    엔드포인트를 두면 인증 경로가 둘이 되고 언젠가 어긋난다.
    """

    def Begin(self, request, context):
        """업로드를 시작한다. 게이트웨이가 segment_id 를 발급하고
        이 차량의 경로로만 유효한 파트별 presigned URL 을 돌려준다.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Complete(self, request, context):
        """모든 파트를 올린 뒤 호출한다. 게이트웨이가 multipart 를 완료하고
        sha256 을 대조한다 — 차량에 맡기지 않는다.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Refresh(self, request, context):
        """진행 중인 업로드의 presigned URL 을 다시 서명한다.

        URL 만료는 15분인데 재연결까지 그보다 오래 걸릴 수 있다. 게이트웨이가 상태를
        갖지 않으므로(§4.1) "어디까지 올렸는지"는 차량과 스토리지가 알고 있고,
        게이트웨이는 같은 upload_id 로 서명만 새로 해준다.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Abort(self, request, context):
        """포기한다. 남은 파트를 지워 스토리지 요금이 새지 않게 한다.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SegmentUploadServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Begin': grpc.unary_unary_rpc_method_handler(
                    servicer.Begin,
                    request_deserializer=ingest__pb2.BeginUploadRequest.FromString,
                    response_serializer=ingest__pb2.BeginUploadResponse.SerializeToString,
            ),
            'Complete': grpc.unary_unary_rpc_method_handler(
                    servicer.Complete,
                    request_deserializer=ingest__pb2.CompleteUploadRequest.FromString,
                    response_serializer=ingest__pb2.CompleteUploadResponse.SerializeToString,
            ),
            'Refresh': grpc.unary_unary_rpc_method_handler(
                    servicer.Refresh,
                    request_deserializer=ingest__pb2.RefreshUrlsRequest.FromString,
                    response_serializer=ingest__pb2.BeginUploadResponse.SerializeToString,
            ),
            'Abort': grpc.unary_unary_rpc_method_handler(
                    servicer.Abort,
                    request_deserializer=ingest__pb2.AbortUploadRequest.FromString,
                    response_serializer=ingest__pb2.AbortUploadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fleetsentinel.ingest.v1.SegmentUpload', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fleetsentinel.ingest.v1.SegmentUpload', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SegmentUpload:
    """── 중량 경로 제어 평면 ────────────────────────────────────────────────

    원시 센서 클립(MCAP, 298~341 MiB)은 **이 채널로 흐르지 않는다.** 게이트웨이는
    presigned URL만 발급하고 데이터는 차량 → 오브젝트 스토리지로 직행한다.
    게이트웨이를 데이터 경로에 넣으면 100대에서
    2.5 GiB/s가 통과해 stateless 확장 이점이 사라진다.

    **REST가 아니라 gRPC인 이유** — 이 채널은 이미 mTLS로 종단되고
    PeerIdentityInterceptor 가 vehicle_id 를 인증서에서 확정한다. 별도 HTTPS
    엔드포인트를 두면 인증 경로가 둘이 되고 언젠가 어긋난다.
    """

    @staticmethod
    def Begin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleetsentinel.ingest.v1.SegmentUpload/Begin',
            ingest__pb2.BeginUploadRequest.SerializeToString,
            ingest__pb2.BeginUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Complete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleetsentinel.ingest.v1.SegmentUpload/Complete',
            ingest__pb2.CompleteUploadRequest.SerializeToString,
            ingest__pb2.CompleteUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Refresh(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleetsentinel.ingest.v1.SegmentUpload/Refresh',
            ingest__pb2.RefreshUrlsRequest.SerializeToString,
            ingest__pb2.BeginUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Abort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleetsentinel.ingest.v1.SegmentUpload/Abort',
            ingest__pb2.AbortUploadRequest.SerializeToString,
            ingest__pb2.AbortUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
